menu:
  首页: /
  TraceInvest: http://traceinvest.com
  随感: /categories/essay/
  技术: /categories/tech/
  理财: /categories/investment/
  生活: /categories/life/
  归档: /archives

widgets:
- search
- tag
- traceInvest
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  weibo: true
  linkedin: true
  google: false
  facebook: false
  twitter: false
  pinterest: false

copyright:
  enable: true
  claim: 版权声明：自由转载-非商用-无演绎-保持署名 @ Creative Commons BY-NC-ND 3.0
  show_link: true

fancybox: true

google_analytics: UA-45019001-1
analytics_site_name: topdna.org
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
